<?php

/**
 * This file is part of the package magicsunday/webtrees-descendants-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\DescendantsChart\Configuration;

/**
 * @var string        $javascript
 * @var Configuration $configuration
 * @var array         $id                The unique chart ID
 * @var array         $chartParams
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var array         $data              The chart data
 */
?>

<div id="webtrees-descendants-chart-container"></div>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script>

const chartParams = <?= $chartParams ?>;
const cssFiles    = <?= json_encode($exportStylesheets) ?>;

const optionGenerations = typeof generations !== "undefined"
    ? generations
    : <?= $configuration->getGenerations() ?>;

const optionLayout = typeof treeLayout !== "undefined"
    ? treeLayout
    : <?= json_encode($configuration->getLayout()) ?>;

// Create chart instance with stored configuration
const descendantsChart = new WebtreesDescendantsChart.DescendantsChart(
    "#webtrees-descendants-chart-container",
    {
        labels      : chartParams.labels,
        generations : optionGenerations,
        treeLayout  : optionLayout,
        rtl         : chartParams.rtl
    }
);

descendantsChart.cssFiles = cssFiles;

// Draw chart
descendantsChart.draw(<?= json_encode($data) ?>);

</script>
<?php View::endpush(); ?>
