<?php

/**
 * This file is part of the package magicsunday/webtrees-descendants-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\DescendantsChart\Configuration;

/**
 * @var string        $javascript
 * @var Configuration $configuration
 * @var array         $id                The unique chart ID
 * @var array         $chartParams
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var array         $data              The chart data
 */
?>

<div class="webtrees-descendants-chart-container" id="webtrees-descendants-chart-container-<?= $id ?>"></div>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script>

// Create chart instance
new WebtreesDescendantsChart.DescendantsChart(
    "#webtrees-descendants-chart-container-<?= $id ?>",
    {
        labels: <?= json_encode($chartParams['labels']) ?>,
        rtl: <?= json_encode($chartParams['rtl']) ?>,
        cssFiles: <?= json_encode($exportStylesheets) ?>,

        get generations() {
            return typeof generations !== "undefined"
                ? generations
                : <?= $configuration->getGenerations() ?>
        },

        get treeLayout() {
            return typeof treeLayout !== "undefined"
                ? treeLayout
                : <?= json_encode($configuration->getLayout()) ?>;
        },

        data: <?= json_encode($data) ?>
    }
);

</script>
<?php View::endpush(); ?>
